# Generated by Django 2.2.1 on 2019-05-22 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('elevator_pitch', models.CharField(max_length=300)),
                ('talk_format', models.IntegerField(choices=[(1, 'Talk(30-45 mins)'), (2, 'Lightning Talks(5-10 mins)'), (3, 'Workshop(more than 60 mins)'), (4, 'Other')])),
                ('auidence_level', models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')])),
                ('description', models.TextField()),
                ('notes', models.TextField()),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('speaker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
