# Generated by Django 2.2 on 2019-06-06 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('events', '0002_conference_organizer'),
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalstatus',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Organizer'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Speaker'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Conference'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='proposal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='proposals.Proposal'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Organizer'),
        ),
    ]
