# Generated by Django 2.2 on 2019-06-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_auto_20190606_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalstatus',
            name='proposal_status',
            field=models.CharField(choices=[('to_be_reviewed', 'Is yet to be reviewed'), ('under_review', 'Being Reviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='to_be_reviewed', max_length=20),
        ),
    ]
