# Generated by Django 2.2 on 2019-05-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190527_2104'),
        ('proposals', '0003_auto_20190528_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='event',
        ),
        migrations.AddField(
            model_name='proposal',
            name='event',
            field=models.ManyToManyField(to='events.Conference'),
        ),
    ]
