# Generated by Django 2.2 on 2019-06-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_auto_20190606_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='content',
            new_name='pitch',
        ),
        migrations.AddField(
            model_name='proposal',
            name='outline',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='proposal',
            name='talktime',
            field=models.IntegerField(choices=[(30, 'Lightning talks'), (90, 'A session'), (180, 'A tutorial')], default=30),
        ),
    ]
