# Generated by Django 2.2 on 2019-06-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0004_auto_20190608_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='title',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
