# Generated by Django 2.2 on 2019-05-28 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190527_2104'),
        ('proposals', '0004_auto_20190528_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='event',
        ),
        migrations.AddField(
            model_name='proposal',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='events.Conference'),
        ),
    ]
