# Generated by Django 2.2 on 2019-06-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0005_proposal_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='slug',
            field=models.SlugField(default=None, unique=True),
        ),
    ]
