# Generated by Django 2.2 on 2019-06-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0006_proposal_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
