# Generated by Django 2.2 on 2019-05-28 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190527_2104'),
        ('proposals', '0007_auto_20190528_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='event',
        ),
        migrations.AddField(
            model_name='proposal',
            name='name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='events.Conference'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
