# Generated by Django 2.2 on 2019-06-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0007_auto_20190616_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalstatus',
            name='proposal_status',
            field=models.CharField(choices=[('to_be_reviewed', 'Is yet to be reviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='to_be_reviewed', max_length=20),
        ),
    ]
