# Generated by Django 2.2 on 2019-05-28 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0010_auto_20190528_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Conference'),
        ),
    ]
