# Generated by Django 2.2 on 2019-06-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(default='')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('venue', models.TextField(default='')),
                ('twitter_id', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
    ]
