# Generated by Django 2.2 on 2019-05-27 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_organizer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('venue', models.TextField(default='')),
                ('twitter_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('organizer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Organizer')),
            ],
        ),
    ]
