# Generated by Django 2.2.1 on 2019-05-22 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='code_of_conduct',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='event_organizer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Organizer'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_website',
            field=models.URLField(blank=True),
        ),
    ]
