# Generated by Django 2.2 on 2019-06-08 09:48

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('events', '0002_conference_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='topic_tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
