# Generated by Django 2.2.1 on 2019-05-22 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190522_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_organizer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.Organizer'),
        ),
    ]
