# Generated by Django 2.2 on 2019-06-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190527_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
