# Generated by Django 2.2 on 2019-06-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_conference_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
