# Generated by Django 2.2 on 2019-06-03 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20190602_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Organizer'),
        ),
    ]
