# Generated by Django 2.2 on 2019-06-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_url', models.URLField(blank=True)),
                ('twitter_handle', models.CharField(blank=True, max_length=15)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('bio', models.TextField(blank=True, max_length=200)),
            ],
        ),
    ]
