# Generated by Django 2.2 on 2019-06-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='organization',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
